version: '3.1'

services:

  app: 
    container_name: potluck
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongo
      
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017

